### ISSUE TITLE
wifi bridge no wireless interface found

### ISSUE THREAD

**Issue by ahmedelhaddad** [binnes/WiFiMeshRaspberryPi#11]
the gateway has been setup successfully (part2) however when i try to implement the wifi bridge model, i seem to have all the wlan connections disappear. 
Do i have to plug in a usb dongle aswell to the rpi just like the gateway?
Is this normal ? 
how to actually connect the bridge to the gateway and start communicating?

**Comment by tim292stro** [comment]
A WiFi adapter can generally do one thing at a time (Master mode as an "AP", Managed mode as a "Client", Ad Hoc as a "Mesh", or Monitor mode as a no-TX "traffic sniffer").
  
You need a second radio to act as a client to another AP before it can act as a wireless gateway (and hopefully on a different frequency/band, to reduce interference) - the alternative is to have your gateway drone fly with a really long network cable to use the ethernet port be your uplink.

Don't laugh...  need a temporary antenna mast 40' above your house to reach over an obstacle like a tree for a Yagi?  It doesn't take much imagination to realize that a DJI uses about 120Watts to fly, and most of that is due to battery weight - meaning you could ground tether a drone and use Type4 PoE (100W), or a hacky PoE injector with a high DC voltage (350-ish, need to be careful to use 600V rated cable!!) to keep it airborne as long as the motors don't overheat.  4-pairs of 23gauge can support just shy of 3Amps max, but you'd have about 1K-Ohm of loss from the Cat-6 round-trip, which is why the voltage needs to be so high.  Then replace the battery with a step down regulator...

**Comment by ahmedelhaddad** [comment]
> A WiFi adapter can generally do one thing at a time (Master mode as an "AP", Managed mode as a "Client", Ad Hoc as a "Mesh", or Monitor mode as a no-TX "traffic sniffer").
> 
> You need a second radio to act as a client to another AP before it can act as a wireless gateway (and hopefully on a different frequency/band, to reduce interference) - the alternative is to have your gateway drone fly with a really long network cable to use the ethernet port be your uplink.
> 
> Don't laugh... need a temporary antenna mast 40' above your house to reach over an obstacle like a tree for a Yagi? It doesn't take much imagination to realize that a DJI uses about 120Watts to fly, and most of that is due to battery weight - meaning you could ground tether a drone and use Type4 PoE (100W), or a hacky PoE injector with a high DC voltage (350-ish, need to be careful to use 600V rated cable!!) to keep it airborne as long as the motors don't overheat. 4-pairs of 23gauge can support just shy of 3Amps max, but you'd have about 1K-Ohm of loss from the Cat-6 round-trip, which is why the voltage needs to be so high. Then replace the battery with a step down regulator...

No offense and thank you for taking the time but I dont know what does this have to do with my inquiry, I just need that error to be solved

**Comment by tim292stro** [comment]
Focus on the first two paragraphs.
  
To "bridge" you need two networks to build a bridge between - but it's just the "structure".  The WiFi adapter can only be one type of network mode (see above).  You can't build a bridge between an Ad Hoc mode network on the same adapter as a Master/Managed mode network - as you can't run both on the same adapter.
  
A "gateway" is a connection from one network to another bigger network.  Think of this like an on-ramp from a city street to a freeway.  If you want to go a long distance quickly, you want to end up on a super-highway with as few stops as possible (i.e. the internet).
  
A "firewall" is a rule enforcer.  Think of this like traffic police standing at your end of the bridge, letting some people cross (ACCEPT), not letting some people pass by throwing them in the river (DROP), and then sending some people to a boarder office for further inspection (FILTER), putting tourists who come from a certain place on a bus to their destination (NAT), and people who belong to your country and have a passport straight across and into the secure city (VPN).
  
To connect between two networks (two sides of a river), you need to build the foundation for the bridge by physically having a place to connect a bridge from/to - most of the instructions in this guide are for getting the mesh network up (it's like you're building an island).  Then you make the connection from your island to the shore of some other network by creating a bridge.  Then you can tell people on your island that they can get to other places faster without as many hops by using the gateway (freeway on-ramp) to the larger network (internet).
  
So, for clarity, your gateway must have two network adapters (either use the built-in WiFi as your mesh and the ethernet as your gateway internet connection - or use an additional WiFi dongle to connect to the internet as a standard client).

**Comment by ahmedelhaddad** [comment]
> Focus on the first two paragraphs.
> 
> To "bridge" you need two networks to build a bridge between - but it's just the "structure". The WiFi adapter can only be one type of network mode (see above). You can't build a bridge between an Ad Hoc mode network on the same adapter as a Master/Managed mode network - as you can't run both on the same adapter.
> 
> A "gateway" is a connection from one network to another bigger network. Think of this like an on-ramp from a city street to a freeway. If you want to go a long distance quickly, you want to end up on a super-highway with as few stops as possible (i.e. the internet).
> 
> A "firewall" is a rule enforcer. Think of this like traffic police standing at your end of the bridge, letting some people cross (ACCEPT), not letting some people pass by throwing them in the river (DROP), and then sending some people to a boarder office for further inspection (FILTER), putting tourists who come from a certain place on a bus to their destination (NAT), and people who belong to your country and have a passport straight across and into the secure city (VPN).
> 
> To connect between two networks (two sides of a river), you need to build the foundation for the bridge by physically having a place to connect a bridge from/to - most of the instructions in this guide are for getting the mesh network up (it's like you're building an island). Then you make the connection from your island to the shore of some other network by creating a bridge. Then you can tell people on your island that they can get to other places faster without as many hops by using the gateway (freeway on-ramp) to the larger network (internet).
> 
> So, for clarity, your gateway must have two network adapters (either use the built-in WiFi as your mesh and the ethernet as your gateway internet connection - or use an additional WiFi dongle to connect to the internet as a standard client).

really nice explanation, I have already set up the gateway with two networks (mobile hotspot and a usb dongle), but when i try to implement whats in part 2 "wifi bridge" , I dont know where to go further from there, how to connect the gateway to the bridge i.e connect the two drones together, also why the WLAN list doesnt appear in order to connect via hotspot
