### ISSUE TITLE
WIFI BRIDGE USING USB DONGLE AS IN PART 2 (URGENT)

### ISSUE THREAD

**Issue by ahmedelhaddad** [binnes/WiFiMeshRaspberryPi#13]
Hello I have the gatewawy working perfectly using usb dongle not ethernet, same goes for the bridge access point using usb dongle with the exception that once i reboot my bridge node I get the NO WLAN INTERFACE FOUND and I cant seem to be able to access the rpi through putty anymore and so I have to use a monitor setup.

I tried all sorts of commands I could find from playing around with dhcpcd or even editing the WPA_supplicant but nothing seems to work.

My question is this supposed to happen, should a bridge node not be able to access the internet? aka my wifi mobile hotspot?

Also when I try running the sudo batctl n on either the gateway or the bridge I dont seem to find neighbours as mentioned.

**Comment by ahmedelhaddad** [comment]
Im also trying to connect to the call code mesh network but says cant connect, Im stuck someone please reply

**Comment by ahmedelhaddad** [comment]
UPDATE: I would still love to know the answer for the above since im struggling however i tried with ethernet connection and fortunately it showed me the neighbours. However the bridge node doesnt have an internet access as in that i have to access it through the monitor and not through Putty, so i cant install the packages mentioned in part3. I tried pinging ibm.com and its working fine so i dont know what to do

**Comment by tim292stro** [comment]
I will have time tomorrow (Pacific Time) to play with this.  What version of PI are you using? 2? 3? 4?

**Comment by ahmedelhaddad** [comment]
> I will have time tomorrow (Pacific Time) to play with this. What version of PI are you using? 2? 3? 4?

Model 4 B

**Comment by tim292stro** [comment]
My apologies, I began work on this over the weekend, but was distracted with real estate shopping.  I have the RPi 4B up to the point of the secondary WiFi - what USB WiFi adapter are you using as the client?

**Comment by ahmedelhaddad** [comment]
> My apologies, I began work on this over the weekend, but was distracted with real estate shopping. I have the RPi 4B up to the point of the secondary WiFi - what USB WiFi adapter are you using as the client?

no problem thank you for taking the time, im using tp link wn725 v3. However i seem to have gotten the bridge up working but now I can't seem to access the gateway node from Putty as before, when I hover abover the wireless networks icon I get "connection to dhcpcd lost". I have downloaded some drivers i found on some forums for v2.

My question is, is it safe to think that the mesh is set up successfully? or do I need to plug in mouse and keyboards everytime?

Note: the verification for the bridge went as mentioned however the gateway's doesn't show the wlan1 option in the "ifconfig" and shows essid any/off in the "iwconfig".

**Comment by tim292stro** [comment]
I don't have that model on-hand, but I ordered one and it should be here tomorrow.

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
