### ISSUE TITLE
WIFI GATEWAY USING HOTSPOT DOESNT SHOW WLAN 1

### ISSUE THREAD

**Issue by ahmedelhaddad** [binnes/WiFiMeshRaspberryPi#14]
ETHERNET works perfectly however i am trying to implement the one in part 2 using hotspot , everything is working fine until i get to the verification step where i run ifconfig in the gateway node and i dont see the wlan1 interface where iwconfig shows wlan1 essid if/any. 
Also when i hover over the wifi connection on my rpi desktop using mouse and keyboard i get the message connection to dhcpcd lost.

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
