### ISSUE TITLE
"interface bat0 is not present" - expected on gateway if no other nodes? 

### ISSUE THREAD

**Issue by mnopneal** [binnes/WiFiMeshRaspberryPi#16]
Thanks for putting this together.    I thought it was very clean to follow.   I thought I had a PI setup as a gateway.    Only minor place I diverged is I ended up putting the start script in root's home directory, but I accounted for that in rc.local. 

I've got an HDMI monitor hooked up to the PI, and on rebooting I can see the above error come up when it hits rc.local.   Actually, the whole message text is: Error - interface bat0 is not present or not a batman-adv interface.

I tried running this as root after boot up and got the same message.  

Since I haven't yet configured another node,  (cause I got to run out and buy some more microSD cards) is that in play here?    Or do I need to back up and figure out this error next? 

Regards, 

Neal

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
