### ISSUE TITLE
Wifi AP on gateway

### ISSUE THREAD

**Issue by Shiroeh** [binnes/WiFiMeshRaspberryPi#17]
Hi, thanks for sharing this, it's been of great help !

Everything works fine, but I've been since some days trying to set up the gateway node also as an AP. I think it can be done but i'm facing some issues, if you had some documents to share or anything it would be of great help !

So far i've been able to either set up a functionnal mesh without an AP on the gateway or an AP on the gateway node but the bride nodes couldn't connect anymore and the client (smartphone) could connect to the AP BUT with an address given by the ethernet connection, while I need the client to get an address from the gateway. 

Thanks for any help you could provide !

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
