### ISSUE TITLE
URGENT 

### ISSUE THREAD

**Issue by Noob25800** [binnes/WiFiMeshRaspberryPi#18]
it was really helpful i manage to build a network i am using 3 pi one is gateway and another one is bridge they both are connected to each other but the third pi is connecting and moreover i want to access internet from all three pi for the third pi I follow all the commands in the file name PMESH. But i am unable to see third pi and cant access internet from my pi.

![2021-07-12 12_29_48-New Issue · binnes_WiFiMeshRaspberryPi](https://user-images.githubusercontent.com/87310358/125280417-ed94d980-e30c-11eb-876a-04bbc9cdba91.png)

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
