### ISSUE TITLE
mtu value of 1532 on host adapter instead of MTU 1468 on bat0 interface 

### ISSUE THREAD

**Issue by basjes1977** [binnes/WiFiMeshRaspberryPi#4]
Thanks for the tutorial, it was very helpful. 
Setting up the mesh and a gateway was a breeze. But I ran in to a problem. 
I had issues pinging and reaching the nodes in the mesh although I successfully set up the mesh network according to your instructions.

I would like to mention that changing the MTU value of the host adapter (wlan0) to 1532 and not setting a MTU value on the bat0 adapter solved my problem with communicating across the mesh.

I hope this can be of help to someone experiencing the same issues I did. In my case only batctl ping worked, normal ping did not. That is until I changed the mtu values as described above.

**Comment by basjes1977** [comment]
So not really an issue anymore, but would be nice to take this up in your tutorial or troubleshooting steps ;)

**Comment by binnes** [comment]
Thanks for the feedback.  I'll repeat the tests you did and update the instructions if needed.

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
