### ISSUE TITLE
Multiple Access points, using same SSID

### ISSUE THREAD

**Issue by ChrisSutton123** [binnes/WiFiMeshRaspberryPi#5]
Sorry if this seems like a dumb question.
But can I setup multiple Access points using the same SSID? One AP on each Mesh node.

**Comment by binnes** [comment]
Hello, Yes this is a valid configuration.  If you ensure all access points have the same SSID and password, then devices should automatically switch to a different access point of the previous one goes out of range.  Ideally you want to ensure that access points closest to each other use a different channel to minimise interference

**Comment by ChrisSutton123** [comment]
Thank you
