### ISSUE TITLE
Remove "sudo batctl gw_mode client" for bridged mesh with no gateway server as it stops DHCP requests working.

### ISSUE THREAD

**Issue by rtozer** [binnes/WiFiMeshRaspberryPi#7]
Thanks for making this tutorial available I found it very useful.

I set up a bridged mesh network to extend my home lan to a number of IOT sensor devices (Pi Zero W) that are in range of each other but not all can see my router AP.

I follower your guide which worked, but encountered the issue  mentioned here: https://github.com/binnes/WiFiMeshRaspberryPi/issues/6
ie errors when trying to get neighbours/origins/stats etc.

So I built batctl to match the batman-adv version as suggested and my mesh stopped working, or rather the mesh came up fine, but no nodes were able to get an IP address so became unreachable.

A diff of batctl 2019.0 vs 2020.4 showed the gw_mode client/server options were only added after 2019.0 so I removed the line "sudo batctl gw_mode client" and everything started working again.
I guess 'gw_mode client' instructs the mesh to look specifically for a gateway server and supresses instead of passing on DHCP requests?

**Comment by binnes** [comment]
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO
